language: python

python:
  - "2.7"

cache: pip

branches:
  only:
    - master
  

script:

  - python ./Aggregate/makeaddin.py
  - git status
  - git add -A
  - git commit -m "addin added"
  - git push
  
after_success:
  - bash ./publish.sh
  # - bash ./make.sh
