# LANGUAGE TO BE USED
language: python


# LANGUAGE VERSION TO BE USED
python:
  - "2.7"

cache: pip

# WORK ONLY ON THE MASTER BRANCH - SAFELIST CONFIGURATION, ELSE USE except INSTEAD OF only
# BOTH only AND except CAN ACCEPT A LIST SEPERATED BY A NEW LINE AND HYPEN
branches:
  only:
    - master
  
# SCRIPT THAT RUNS THE NEEDED COMPILATION
script:
  - ls ./Aggregate
  - python ./Aggregate/makeaddin.py
  - ls ./Aggregate
  - git status
  - git add -A
  - git commit -m "addin created"
  - git remote add origin https://sriramab:$sriramab_KEY@github.com/sriramab/ArcGISAddins.git
  - git push origin master
  #- git add -A
  #- git commit -m "addin created"
  #- git push
  
# SCRIPT THAT RUNS IF THE ABOVE COMPILATION IS SUCCESSFUL
after_success:
  - bash ./publish.sh
  
