language: python

python:
  - "2.7"

cache: pip

branches:
    only:
        - master

install:
    pip install --user -r requirements.txt
  

script:

  - python Aggregate/makeaddin.py
  
after_success:
  - bash ./publish.sh
