language: python

python:
  - "2.7"

cache: pip

branches:
  only:
    - master
  

script:
  - ls ./Aggregate
  - python ./Aggregate/makeaddin.py
  - ls ./Aggregate
  #- git status
  #- git add -A
  #- git commit -m "addin added"
  #- git push
  
after_success:
  - bash ./publish.sh
  # - bash ./make.sh
